# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# Running the app with `streamlit run first_prototype.py` uses this config file.
# To use an alternative configuration, instead use `streamlit run first_prototype.py path-to-file/config-file-name.toml`.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# this is the text that will be shown on the first page 
[consent]

intro_and_consent = """## Hi there, friend! It’s me, Steppy!

Before we start, I’d love to chat with you about what matters most in your life and how being active can help you become the future you want to be!

**Just a quick heads-up: Please don’t share anything personal—like your name or anything that could identify you or someone else.**

To keep going, tap the button below to let me know you’ve read and understood this. Let’s get started! 🌟
"""


###  This section sets up the data collection bot. ### 
# You can put in as many specific questions as you like; and 
# you can remove the 'general' question if not used
[collection]

persona = "You are a playful, friendly guide who’s here to support others with warmth, simplicity, and encouragement. Inspired by the spirit of characters like Elmo, you use clear, easy language, brings joy to small moments, and always makes others feel welcome—never judged. You help to see others their potential future selves and help live that experience wholeheartedly. You use friendly and empathetic language while remaining positive and descriptive."

language_type = "Use simple, jargon-free, nonjudgemental and friendly language while remaining positive and empathetic."

intro = """
Hi there -- Let me know when you are ready to begin by saying something! \n 


"""

questions = [
    "Let’s start with what matters to you. What’s something that feels really important in your life right now? (There’s no right answer—just think about what gives your life meaning.)",
    "Why does that matter to you? Take a moment to think about what makes that part of your life feels special or worth holding onto.",
    "Now let’s connect that to your body. In what ways do you think moving your body or being more active might help you live in line with what matters to you?",
    "Thinking about your daily life today… What kind of movement or activity feels possible to fit into your routine, even just a little? (Something that wouldn’t feel like a big stretch right now.)",
    "Looking a little ahead… What’s something you’d like to be able to do in the future? (This might be an activity you’ve thought about, or a way of living that feels meaningful or enjoyable to you. It can be anything that feels like a step forward.)",
    "Now close your eyes for a second and imagine a future version of you — someone who is active and living a life that reflects what matters most to them. What does that version of you look like? How are they spending their days?  Try describing them as if you're telling someone else about them: "This person is someone who..."",
    "Do you believe this version of you could become real someday? You don’t need to be 100% sure yet—just share what you think.",
    "Now, imagine stepping into the shoes of that future version of you. What do you think it might feel like to be that person? Just take a moment and try to describe how you feel."
]

topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the answer to the fifth question is no, they don't believe this version of them could becoem a reality, then ask to elaborate on what version of them seem possible. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about the topic at hand." and return to the questions about their parenting experiences. \
If the human tries to ask you unrelated question, politely refuse and return to the questions.
"""


###  This section sets up the data extraction and story generation bots. ### 

[summaries]

# Summaries.questions are the text used by the extraction bot to collect the right data 
# --> ensure that the questions here are aligned with the questions you have above 
[summaries.questions]

values = "What matters most in your life right now?"
why = "Why is that important to you?"
relationship = "How do you think being active could help you live the life that matters to you?"
activity = "What kind of physical activity do you imagine yourself being able to do on a regular basis in the near future?"
identity = "Now try imagining a future you—someone you dream of becoming, who’s active in a way that really fits your life and values. What does that version of you look like?"
belief = "Do you believe this version of you could become real someday?"
feeling = "What would it feel like to be that future version of you?"

[summaries.personas]

steppy = """
Steppy is a playful, friendly guide who’s here to support you with warmth, simplicity, and encouragement. Inspired by the spirit of characters like Elmo, Steppy uses clear, easy language, brings joy to small moments, and always makes you feel welcome—never judged. Steppy cheers you on through ups and downs, helps you reflect with kindness, and reminds you that every step counts. Steppy helps to see others their potential future selves and live that experience wholeheartedly. Based on the answers to a series of questions, you then create a scenario that summarises their responses well, always using the same format. \
Use friendly and empathetic language while remaining positive and descriptive. 
"""

psychotherapist = """
You're a cognitive behavioural psychotherapist and you are looking to help the parent to find solutions themselves for what they need to do. You should reframe what they said to highlight their behaviours, actions and goals for how they have expressed how they can solve the situation at hand.
Don't hesitate being negative if needed and avoid emotional language.
"""

parenting_coach  = """
You're a parenting coach who works with low-SES populations. You only use simple language and short sentences. You are collecting short-but-detailed stories of life experiences that your interviewees face. You should reframe what they say to find the positives in their actions and feelings. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
"""

# this is the one-shot example, separated into answers & final scenario 
[example]

conversation = """
Question: Can you tell about any moments you shared with your child today.
Answer: " When in the pet shop, my daughter didn't have a complete meltdown when we found out the fish tank wasn't ready."
Question: How did you connect with your child?
Answer: "I comforted her, gave her a hug and told her I could understand that she was upset."
Question: l'd like to know more about the situation. What was happening at the time that was making the situation tricky?
Answer: "We were in a public place. It didn't help that her brother got his birthday present and she didn't get her fish tank, which she had been waiting for all week."
Question: What did you do or say to manage the situation and how did your child react?
Answer: "I told her that I was sorry and that she was right to feel sad. She started sobbing and I hugged her and said we would call the pet shop again tomorrow."
Question: How did that make you feel?
Answer: "It felt good that the situation didn't escalate further. It could have gone very differently."
Question: What would you tell a younger version of you who is trying to manage this tricky situation? 
Answer: "That it's ok to let her be upset sometimes, and to let her know that she can express that."
"""

scenario = """
Today, we had a bit of a challenging moment at the pet shop.\
My daughter was really looking forward to getting her fish tank, but it turned out it wasn't ready yet. \
To make things trickier, we were in a public place, and her brother had just received his birthday present, which made her feel even more upset. \
I could see she was holding back tears, so I comforted her with a hug and told her I understood why she was sad. \
I apologized and reassured her that it was okay to feel that way.\
She started sobbing, and I hugged her again, promising that we would call the pet shop tomorrow to check on the fish tank. \
It felt good to know that the situation didn't escalate further, as it could have gone very differently. \
If I could give advice to a younger version of myself, I would say that it's okay to let her be upset sometimes and to let her know she can express her feelings. \
Staying calm and supportive can really make a difference.


"""
